INSERT INTO tblmedicamento(descripcion) VALUES ('Vincristina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Daunorubicina (daunomycin)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Doxorrubicina (Adriamicina)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Idarubicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Citarabina (arabinósido de citosina o ara-C)');
INSERT INTO tblmedicamento(descripcion) VALUES ('L-asparaginasa, PEG-L-asparaginasa (pegaspargasa)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Etopósido');
INSERT INTO tblmedicamento(descripcion) VALUES ('6-mercaptopurina (6-MP)');
INSERT INTO tblmedicamento(descripcion) VALUES ('6-tioguanina (6-TG)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metotrexato');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mitoxantrona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciclofosfamida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Corticoesteroides como prednisona, prednisolona o dexametasona, o hidrocortisona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Aciclovir');
INSERT INTO tblmedicamento(descripcion) VALUES ('Acitromicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Alopurinol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Amikacina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Amitriptilina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Anfotericina B');
INSERT INTO tblmedicamento(descripcion) VALUES ('Aprepitant para pacientes con cáncer infantil');
INSERT INTO tblmedicamento(descripcion) VALUES ('Asparaginasa Erwinia');
INSERT INTO tblmedicamento(descripcion) VALUES ('Bleomicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Blinatumomab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Bortezomib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Brentuximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Busulfan');
INSERT INTO tblmedicamento(descripcion) VALUES ('Carboplatino');
INSERT INTO tblmedicamento(descripcion) VALUES ('Cefepima');
INSERT INTO tblmedicamento(descripcion) VALUES ('Cefixima');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ceftriaxona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciclofosfamida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciclosforina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciprofloxacina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciproheptadina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Cisplatino');
INSERT INTO tblmedicamento(descripcion) VALUES ('Citarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Clofarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Crizotinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dactinomicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dasatinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Daunorrubicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dexametasona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dexrazoxano');
INSERT INTO tblmedicamento(descripcion) VALUES ('Difenhidramina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dinutuximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Docetaxel');
INSERT INTO tblmedicamento(descripcion) VALUES ('Docusato');
INSERT INTO tblmedicamento(descripcion) VALUES ('Doxorrubicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Etopósido');
INSERT INTO tblmedicamento(descripcion) VALUES ('Famciclovir');
INSERT INTO tblmedicamento(descripcion) VALUES ('Fentanilo');
INSERT INTO tblmedicamento(descripcion) VALUES ('Filgrastim');
INSERT INTO tblmedicamento(descripcion) VALUES ('Fludarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Fluorouracilo');
INSERT INTO tblmedicamento(descripcion) VALUES ('Gabapentina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ganciclovir');
INSERT INTO tblmedicamento(descripcion) VALUES ('Gemcitabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Gemtuzumab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Granisetrón');
INSERT INTO tblmedicamento(descripcion) VALUES ('Hidrocodona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ifosfamida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Imatinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Inotuzumab ozogamicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Interferón alfa-2b');
INSERT INTO tblmedicamento(descripcion) VALUES ('Interleucina-2');
INSERT INTO tblmedicamento(descripcion) VALUES ('Irinotecán');
INSERT INTO tblmedicamento(descripcion) VALUES ('Isotretinoína');
INSERT INTO tblmedicamento(descripcion) VALUES ('Leucovorina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Levetiracetam');
INSERT INTO tblmedicamento(descripcion) VALUES ('Levofloxacino');
INSERT INTO tblmedicamento(descripcion) VALUES ('Lidocaína');
INSERT INTO tblmedicamento(descripcion) VALUES ('Lorazepam');
INSERT INTO tblmedicamento(descripcion) VALUES ('Melfalán');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mercaptopurina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mesna');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metadona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metilprednisolona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metotrexato');
INSERT INTO tblmedicamento(descripcion) VALUES ('Micafungina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mitotano');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mitoxantrona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Morfina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Nelarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Nivolumab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Omeprazol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ondansetrón');
INSERT INTO tblmedicamento(descripcion) VALUES ('Oxicodona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Paclitaxel');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pazopanib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pegaspargasa');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pegfilgrastim');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pentamidina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Polietilenglicol 3350');
INSERT INTO tblmedicamento(descripcion) VALUES ('Posaconazol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Prednisona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Procarbazina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Rasburicase');
INSERT INTO tblmedicamento(descripcion) VALUES ('Rituximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ruxolitinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sen');
INSERT INTO tblmedicamento(descripcion) VALUES ('Siltuximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sirolimús');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sorafenib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sulfametoxazol/trimetoprima');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sunitinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tacrolimus');
INSERT INTO tblmedicamento(descripcion) VALUES ('Temozolomida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Temsirolimus');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tioguanina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tiotepa');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tisagenlecleucel');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tobramicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tocilizumab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Topotecán');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tretinoína');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vancomicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vemurafenib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vinblastina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vincristina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vismodegib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Voriconazol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vorinostat');


INSERT INTO `tbldiagnosticocie` VALUES ('C90.1', 'Leucemia de células plasmáticas', 'Leucemia de células plasmáticas C90.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C90.2', 'Plasmocitoma, extramedular', 'Plasmocitoma, extramedular C90.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91', 'Leucemia linfoide', 'Leucemia linfoide C91\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.0', 'Leucemia linfoblástica aguda', 'Leucemia linfoblástica aguda C91.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.1', 'Leucemia linfocítica crónica', 'Leucemia linfocítica crónica C91.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.2', 'Leucemia linfocítica subaguda', 'Leucemia linfocítica subaguda C91.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.3', 'Leucemia prolinfocítica', 'Leucemia prolinfocítica C91.3\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.4', 'Leucemia de células vellosas', 'Leucemia de células vellosas C91.4\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.5', 'Leucemia de células T adultas', 'Leucemia de células T adultas C91.5\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.7', 'Otras leucemias linfoides', 'Otras leucemias linfoides C91.7\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C91.9', 'Leucemia linfoide, sin otra especificación', 'Leucemia linfoide, sin otra especificación C91.9\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92', 'Leucemia mieloide', 'Leucemia mieloide C92\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.0', 'Leucemia mieloide aguda', 'Leucemia mieloide aguda C92.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.1', 'Leucemia mieloide crónica', 'Leucemia mieloide crónica C92.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.2', 'Leucemia mieloide subaguda', 'Leucemia mieloide subaguda C92.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.3', 'Sarcoma mieloide', 'Sarcoma mieloide C92.3\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.4', 'Leucemia promielocítica aguda', 'Leucemia promielocítica aguda C92.4\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.5', 'Leucemia mielomonocítica aguda', 'Leucemia mielomonocítica aguda C92.5\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.7', 'Otras leucemias mieloides', 'Otras leucemias mieloides C92.7\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C92.9', 'Leucemia mieloide, sin otra especificación', 'Leucemia mieloide, sin otra especificación C92.9\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C93', 'Leucemia monocítica', 'Leucemia monocítica C93\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C93.0', 'Leucemia monocítica aguda', 'Leucemia monocítica aguda C93.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C93.1', 'Leucemia monocítica crónica', 'Leucemia monocítica crónica C93.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C93.2', 'Leucemia monocítica subaguda', 'Leucemia monocítica subaguda C93.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C93.7', 'Otras leucemias monocíticas', 'Otras leucemias monocíticas C93.7\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C93.9', 'Leucemia monocítica, sin otra especificación', 'Leucemia monocítica, sin otra especificación C93.9\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94', 'Otras leucemias de tipo celular especificado', 'Otras leucemias de tipo celular especificado C94\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.0', 'Eritremia aguda y eritroleucemia', 'Eritremia aguda y eritroleucemia C94.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.1', 'Eritremia crónica', 'Eritremia crónica C94.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.2', 'Leucemia megacarioblástica aguda', 'Leucemia megacarioblástica aguda C94.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.3', 'Leucemia de mastocitos', 'Leucemia de mastocitos C94.3\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.4', 'Panmielosis aguda', 'Panmielosis aguda C94.4\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.5', 'Mielofibrosis aguda', 'Mielofibrosis aguda C94.5\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C94.7', 'Otras leucemias especificadas', 'Otras leucemias especificadas C94.7\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C95', 'Leucemia de células de tipo no especificado', 'Leucemia de células de tipo no especificado C95\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C95.0', 'Leucemia aguda, células de tipo no especificado', 'Leucemia aguda, células de tipo no especificado C95.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C95.1', 'Leucemia crónica, células de tipo no especificado', 'Leucemia crónica, células de tipo no especificado C95.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C95.2', 'Leucemia subaguda, células de tipo no especificado', 'Leucemia subaguda, células de tipo no especificado C95.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C95.7', 'Otras leucemias de células de tipo no especificado', 'Otras leucemias de células de tipo no especificado C95.7\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C95.9', 'Leucemia, no especificada', 'Leucemia, no especificada C95.9\r');


INSERT INTO `tbldiagnosticocie` VALUES ('C96.3', 'Linfoma histiocítico verdadero', 'Linfoma histiocítico verdadero C96.3\r');
INSERT INTO `tbldiagnosticocie` VALUES ('B21.2', 'Enfermedad por VIH, resultante en otros tipos de linfoma no Hodgkin', 'Enfermedad por VIH, resultante en otros tipos de linfoma no Hodgkin B21.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C82', 'Linfoma no Hodgkin folicular [nodular]', 'Linfoma no Hodgkin folicular [nodular] C82\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C82.0', 'Linfoma no Hodgkin de células pequeñas hendidas, folicular', 'Linfoma no Hodgkin de células pequeñas hendidas, folicular C82.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C82.1', 'Linfoma no Hodkin mixto, de pequeñas células hendidas y de grandes células, folicular', 'Linfoma no Hodkin mixto, de pequeñas células hendidas y de grandes células, folicular C82.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C82.2', 'Linfoma no Hodgkin de células grandes, folicular', 'Linfoma no Hodgkin de células grandes, folicular C82.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C82.7', 'Otros tipos especificados de linfoma no Hodgkin folicular', 'Otros tipos especificados de linfoma no Hodgkin folicular C82.7\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C82.9', 'Linfoma no Hodgkin folicular, sin otra especificación', 'Linfoma no Hodgkin folicular, sin otra especificación C82.9\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83', 'Linfoma no Hodgkin difuso', 'Linfoma no Hodgkin difuso C83\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.0', 'Linfoma no Hodgkin de células pequeñas (difuso)', 'Linfoma no Hodgkin de células pequeñas (difuso) C83.0\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.1', 'Linfoma no Hodgkin de células pequeñas hendidas (difuso)', 'Linfoma no Hodgkin de células pequeñas hendidas (difuso) C83.1\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.2', 'Linfoma no Hodgkin mixto, de células pequeñas y grandes (difuso)', 'Linfoma no Hodgkin mixto, de células pequeñas y grandes (difuso) C83.2\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.3', 'Linfoma no Hodgkin de células grandes (difuso)', 'Linfoma no Hodgkin de células grandes (difuso) C83.3\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.4', 'Linfoma no Hodgkin inmunoblástico (difuso)', 'Linfoma no Hodgkin inmunoblástico (difuso) C83.4\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.5', 'Linfoma no Hodgkin linfoblástico (difuso)', 'Linfoma no Hodgkin linfoblástico (difuso) C83.5\r');
INSERT INTO `tbldiagnosticocie` VALUES ('C83.6', 'Linfoma no Hodgkin indiferenciado (difuso)', 'Linfoma no Hodgkin indiferenciado (difuso) C83.6\r');

-- Agregado de diagnositicos tipo TUMOR
INSERT INTO tbldiagnosticocie VALUES ('C01','Tumor maligno de la base de la lengua', 'Tumor maligno de la base de la lengua C01');
INSERT INTO tbldiagnosticocie VALUES ('C03','Tumor maligno de la encía','Tumor maligno de la encía C03');
INSERT INTO tbldiagnosticocie VALUES ('C04','Tumor maligno del piso de la boca','Tumor maligno del piso de la boca C04');
INSERT INTO tbldiagnosticocie VALUES ('C05','Tumor maligno del paladar','Tumor maligno del paladar C05');
INSERT INTO tbldiagnosticocie VALUES ('C06','Tumor maligno de otras partes y de las no especificadas','Tumor maligno de otras partes y de las no especificadas');
INSERT INTO tbldiagnosticocie VALUES ('C07','Tumor maligno de la glándula parótida','Tumor maligno de la glándula parótida C07');
INSERT INTO tbldiagnosticocie VALUES ('C08','Tumor maligno de otras glándulas salivales mayores','Tumor maligno de otras glándulas salivales mayores');
INSERT INTO tbldiagnosticocie VALUES ('C09','Tumor maligno de la amígdala','Tumor maligno de la amígdala C09');
INSERT INTO tbldiagnosticocie VALUES ('C10','Tumor maligno de la orofaringe','Tumor maligno de la orofaringe C10');