INSERT INTO tblmedicamento(descripcion) VALUES ('Vincristina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Daunorubicina (daunomycin)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Doxorrubicina (Adriamicina)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Idarubicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Citarabina (arabinósido de citosina o ara-C)');
INSERT INTO tblmedicamento(descripcion) VALUES ('L-asparaginasa, PEG-L-asparaginasa (pegaspargasa)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Etopósido');
INSERT INTO tblmedicamento(descripcion) VALUES ('6-mercaptopurina (6-MP)');
INSERT INTO tblmedicamento(descripcion) VALUES ('6-tioguanina (6-TG)');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metotrexato');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mitoxantrona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciclofosfamida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Corticoesteroides como prednisona, prednisolona o dexametasona, o hidrocortisona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Aciclovir');
INSERT INTO tblmedicamento(descripcion) VALUES ('Acitromicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Alopurinol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Amikacina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Amitriptilina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Anfotericina B');
INSERT INTO tblmedicamento(descripcion) VALUES ('Aprepitant para pacientes con cáncer infantil');
INSERT INTO tblmedicamento(descripcion) VALUES ('Asparaginasa Erwinia');
INSERT INTO tblmedicamento(descripcion) VALUES ('Bleomicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Blinatumomab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Bortezomib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Brentuximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Busulfan');
INSERT INTO tblmedicamento(descripcion) VALUES ('Carboplatino');
INSERT INTO tblmedicamento(descripcion) VALUES ('Cefepima');
INSERT INTO tblmedicamento(descripcion) VALUES ('Cefixima');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ceftriaxona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciclofosfamida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciclosforina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciprofloxacina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ciproheptadina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Cisplatino');
INSERT INTO tblmedicamento(descripcion) VALUES ('Citarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Clofarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Crizotinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dactinomicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dasatinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Daunorrubicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dexametasona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dexrazoxano');
INSERT INTO tblmedicamento(descripcion) VALUES ('Difenhidramina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Dinutuximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Docetaxel');
INSERT INTO tblmedicamento(descripcion) VALUES ('Docusato');
INSERT INTO tblmedicamento(descripcion) VALUES ('Doxorrubicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Etopósido');
INSERT INTO tblmedicamento(descripcion) VALUES ('Famciclovir');
INSERT INTO tblmedicamento(descripcion) VALUES ('Fentanilo');
INSERT INTO tblmedicamento(descripcion) VALUES ('Filgrastim');
INSERT INTO tblmedicamento(descripcion) VALUES ('Fludarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Fluorouracilo');
INSERT INTO tblmedicamento(descripcion) VALUES ('Gabapentina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ganciclovir');
INSERT INTO tblmedicamento(descripcion) VALUES ('Gemcitabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Gemtuzumab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Granisetrón');
INSERT INTO tblmedicamento(descripcion) VALUES ('Hidrocodona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ifosfamida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Imatinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Inotuzumab ozogamicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Interferón alfa-2b');
INSERT INTO tblmedicamento(descripcion) VALUES ('Interleucina-2');
INSERT INTO tblmedicamento(descripcion) VALUES ('Irinotecán');
INSERT INTO tblmedicamento(descripcion) VALUES ('Isotretinoína');
INSERT INTO tblmedicamento(descripcion) VALUES ('Leucovorina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Levetiracetam');
INSERT INTO tblmedicamento(descripcion) VALUES ('Levofloxacino');
INSERT INTO tblmedicamento(descripcion) VALUES ('Lidocaína');
INSERT INTO tblmedicamento(descripcion) VALUES ('Lorazepam');
INSERT INTO tblmedicamento(descripcion) VALUES ('Melfalán');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mercaptopurina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mesna');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metadona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metilprednisolona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Metotrexato');
INSERT INTO tblmedicamento(descripcion) VALUES ('Micafungina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mitotano');
INSERT INTO tblmedicamento(descripcion) VALUES ('Mitoxantrona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Morfina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Nelarabina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Nivolumab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Omeprazol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ondansetrón');
INSERT INTO tblmedicamento(descripcion) VALUES ('Oxicodona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Paclitaxel');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pazopanib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pegaspargasa');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pegfilgrastim');
INSERT INTO tblmedicamento(descripcion) VALUES ('Pentamidina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Polietilenglicol 3350');
INSERT INTO tblmedicamento(descripcion) VALUES ('Posaconazol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Prednisona');
INSERT INTO tblmedicamento(descripcion) VALUES ('Procarbazina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Rasburicase');
INSERT INTO tblmedicamento(descripcion) VALUES ('Rituximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Ruxolitinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sen');
INSERT INTO tblmedicamento(descripcion) VALUES ('Siltuximab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sirolimús');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sorafenib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sulfametoxazol/trimetoprima');
INSERT INTO tblmedicamento(descripcion) VALUES ('Sunitinib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tacrolimus');
INSERT INTO tblmedicamento(descripcion) VALUES ('Temozolomida');
INSERT INTO tblmedicamento(descripcion) VALUES ('Temsirolimus');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tioguanina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tiotepa');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tisagenlecleucel');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tobramicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tocilizumab');
INSERT INTO tblmedicamento(descripcion) VALUES ('Topotecán');
INSERT INTO tblmedicamento(descripcion) VALUES ('Tretinoína');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vancomicina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vemurafenib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vinblastina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vincristina');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vismodegib');
INSERT INTO tblmedicamento(descripcion) VALUES ('Voriconazol');
INSERT INTO tblmedicamento(descripcion) VALUES ('Vorinostat');

INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C00', 'Tumor maligno del labio');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C34', 'Tumor maligno de los bronquios y del pulmón, parte no especificada');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C56', 'Tumor maligno del ovario');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C70', 'Tumor maligno de las meninges');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C81', 'Linfoma de Hodgkin');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C90', 'Leucemia de células precursoras de linfocitos B');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C91', 'Leucemia linfoblástica aguda');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C94', 'Leucemia de células de la granulación eosinófila');
INSERT INTO tblDiagnosticoCIE(codigo_cie, descripcion) VALUES('C40', 'Tumor maligno de los huesos y del cartílago articular de los miembros');
