INSERT INTO tblmedicamentos(descripcion) VALUES ('Vincristina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Daunorubicina (daunomycin)');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Doxorrubicina (Adriamicina)');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Idarubicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Citarabina (arabinósido de citosina o ara-C)');
INSERT INTO tblmedicamentos(descripcion) VALUES ('L-asparaginasa, PEG-L-asparaginasa (pegaspargasa)');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Etopósido');
INSERT INTO tblmedicamentos(descripcion) VALUES ('6-mercaptopurina (6-MP)');
INSERT INTO tblmedicamentos(descripcion) VALUES ('6-tioguanina (6-TG)');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Metotrexato');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Mitoxantrona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ciclofosfamida');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Corticoesteroides como prednisona, prednisolona o dexametasona, o hidrocortisona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Aciclovir');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Acitromicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Alopurinol');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Amikacina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Amitriptilina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Anfotericina B');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Aprepitant para pacientes con cáncer infantil');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Asparaginasa Erwinia');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Bleomicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Blinatumomab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Bortezomib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Brentuximab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Busulfan');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Carboplatino');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Cefepima');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Cefixima');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ceftriaxona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ciclofosfamida');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ciclosforina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ciprofloxacina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ciproheptadina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Cisplatino');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Citarabina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Clofarabina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Crizotinib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Dactinomicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Dasatinib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Daunorrubicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Dexametasona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Dexrazoxano');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Difenhidramina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Dinutuximab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Docetaxel');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Docusato');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Doxorrubicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Etopósido');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Famciclovir');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Fentanilo');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Filgrastim');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Fludarabina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Fluorouracilo');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Gabapentina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ganciclovir');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Gemcitabina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Gemtuzumab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Granisetrón');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Hidrocodona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ifosfamida');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Imatinib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Inotuzumab ozogamicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Interferón alfa-2b');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Interleucina-2');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Irinotecán');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Isotretinoína');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Leucovorina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Levetiracetam');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Levofloxacino');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Lidocaína');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Lorazepam');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Melfalán');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Mercaptopurina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Mesna');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Metadona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Metilprednisolona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Metotrexato');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Micafungina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Mitotano');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Mitoxantrona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Morfina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Nelarabina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Nivolumab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Omeprazol');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ondansetrón');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Oxicodona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Paclitaxel');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Pazopanib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Pegaspargasa');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Pegfilgrastim');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Pentamidina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Polietilenglicol 3350');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Posaconazol');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Prednisona');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Procarbazina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Rasburicase');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Rituximab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Ruxolitinib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Sen');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Siltuximab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Sirolimús');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Sorafenib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Sulfametoxazol/trimetoprima');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Sunitinib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tacrolimus');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Temozolomida');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Temsirolimus');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tioguanina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tiotepa');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tisagenlecleucel');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tobramicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tocilizumab');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Topotecán');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Tretinoína');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Vancomicina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Vemurafenib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Vinblastina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Vincristina');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Vismodegib');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Voriconazol');
INSERT INTO tblmedicamentos(descripcion) VALUES ('Vorinostat');



INSERT INTO `tblusuario` VALUES (1, 'Administrador', 'Administrador', '123321', 'ADMIN', '1999-12-12', NULL, NULL, '$2y$10$LMcE3IMBlFOgb1MECPqJk.vgK8jopdox04BVOdBPThfE0eHOmrBbu', NULL, NULL, NULL, NULL, 'ad@mail.com', NULL);
INSERT INTO `tblusuario` VALUES (2, 'Sisaño Pardel', 'Roberto', '123321', 'MEDICO', '1988-02-12', 'ONCOLOGIA', 'M', '$2y$10$LMcE3IMBlFOgb1MECPqJk.vgK8jopdox04BVOdBPThfE0eHOmrBbu', NULL, '2023-09-27 00:38:02', '2023-09-27 00:38:02', '79656767', 'xdd@mail.com', NULL);
INSERT INTO `tblusuario` VALUES (3, 'Baldomero', 'Regina', '311123112', 'PACIENTE', '2000-02-21', NULL, 'F', '$2y$10$r3VZtImzhbzJ.4azjLaOT.tHkUSuqJLiWE/0yEh9pvWhnpwtw5S8u', NULL, '2023-09-27 00:44:53', '2023-09-27 00:44:53', '77867567', 'admin@mail.com', '667767DA12');