-- MEDICAMENTOS INSERT
INSERT INTO tblmedicamento (descripcion) VALUES('tblVincristina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDaunorubicina (daunomycin)');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDoxorrubicina (Adriamicina)');
INSERT INTO tblmedicamento (descripcion) VALUES('tblIdarubicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCitarabina (arabinósido de citosina o ara-C)');
INSERT INTO tblmedicamento (descripcion) VALUES('tblL-asparaginasa, PEG-L-asparaginasa (pegaspargasa)');
INSERT INTO tblmedicamento (descripcion) VALUES('tblEtopósido');
INSERT INTO tblmedicamento (descripcion) VALUES('tbl6-mercaptopurina (6-MP)');
INSERT INTO tblmedicamento (descripcion) VALUES('tbl6-tioguanina (6-TG)');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMetotrexato');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMitoxantrona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCiclofosfamida');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCorticoesteroides como prednisona, prednisolona o dexametasona, o hidrocortisona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAciclovir');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAcitromicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAlopurinol');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAmikacina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAmitriptilina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAnfotericina B');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAprepitant para pacientes con cáncer infantil');
INSERT INTO tblmedicamento (descripcion) VALUES('tblAsparaginasa Erwinia');
INSERT INTO tblmedicamento (descripcion) VALUES('tblBleomicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblBlinatumomab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblBortezomib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblBrentuximab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblBusulfan');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCarboplatino');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCefepima');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCefixima');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCeftriaxona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCiclofosfamida');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCiclosforina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCiprofloxacina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCiproheptadina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCisplatino');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCitarabina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblClofarabina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblCrizotinib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDactinomicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDasatinib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDaunorrubicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDexametasona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDexrazoxano');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDifenhidramina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDinutuximab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDocetaxel');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDocusato');
INSERT INTO tblmedicamento (descripcion) VALUES('tblDoxorrubicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblEtopósido');
INSERT INTO tblmedicamento (descripcion) VALUES('tblFamciclovir');
INSERT INTO tblmedicamento (descripcion) VALUES('tblFentanilo');
INSERT INTO tblmedicamento (descripcion) VALUES('tblFilgrastim');
INSERT INTO tblmedicamento (descripcion) VALUES('tblFludarabina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblFluorouracilo');
INSERT INTO tblmedicamento (descripcion) VALUES('tblGabapentina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblGanciclovir');
INSERT INTO tblmedicamento (descripcion) VALUES('tblGemcitabina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblGemtuzumab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblGranisetrón');
INSERT INTO tblmedicamento (descripcion) VALUES('tblHidrocodona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblIfosfamida');
INSERT INTO tblmedicamento (descripcion) VALUES('tblImatinib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblInotuzumab ozogamicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblInterferón alfa-2b');
INSERT INTO tblmedicamento (descripcion) VALUES('tblInterleucina-2');
INSERT INTO tblmedicamento (descripcion) VALUES('tblIrinotecán');
INSERT INTO tblmedicamento (descripcion) VALUES('tblIsotretinoína');
INSERT INTO tblmedicamento (descripcion) VALUES('tblLeucovorina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblLevetiracetam');
INSERT INTO tblmedicamento (descripcion) VALUES('tblLevofloxacino');
INSERT INTO tblmedicamento (descripcion) VALUES('tblLidocaína');
INSERT INTO tblmedicamento (descripcion) VALUES('tblLorazepam');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMelfalán');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMercaptopurina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMesna');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMetadona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMetilprednisolona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMetotrexato');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMicafungina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMitotano');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMitoxantrona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblMorfina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblNelarabina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblNivolumab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblOmeprazol');
INSERT INTO tblmedicamento (descripcion) VALUES('tblOndansetrón');
INSERT INTO tblmedicamento (descripcion) VALUES('tblOxicodona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPaclitaxel');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPazopanib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPegaspargasa');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPegfilgrastim');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPentamidina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPolietilenglicol 3350');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPosaconazol');
INSERT INTO tblmedicamento (descripcion) VALUES('tblPrednisona');
INSERT INTO tblmedicamento (descripcion) VALUES('tblProcarbazina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblRasburicase');
INSERT INTO tblmedicamento (descripcion) VALUES('tblRituximab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblRuxolitinib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblSen');
INSERT INTO tblmedicamento (descripcion) VALUES('tblSiltuximab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblSirolimús');
INSERT INTO tblmedicamento (descripcion) VALUES('tblSorafenib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblSulfametoxazol/trimetoprima');
INSERT INTO tblmedicamento (descripcion) VALUES('tblSunitinib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTacrolimus');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTemozolomida');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTemsirolimus');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTioguanina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTiotepa');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTisagenlecleucel');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTobramicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTocilizumab');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTopotecán');
INSERT INTO tblmedicamento (descripcion) VALUES('tblTretinoína');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVancomicina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVemurafenib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVinblastina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVincristina');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVismodegib');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVoriconazol');
INSERT INTO tblmedicamento (descripcion) VALUES('tblVorinostat');

-- INSERTS CIE
